name = "care-radi0"
main = "./worker.js"
compatibility_date = "2026-09-01"
keep_vars = true

[assets]
directory = "./"
binding = "ASSETS"
run_worker_first = [
  "/itunes/*",
  "/deezer/*",
  "/api/*",
  "/admin/*"
]

[[d1_databases]]
binding = "DB"
database_name = "care-radi0-submissions"
database_id = "6b613a8b-5a9e-4855-a4b1-c9482ba0a150"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true
